insert(tree.root, 19);
insert(tree.root, 29);
insert(tree.root, 99);
insert(tree.root, 9);
insert(tree.root, 2);
insert(tree.root, 32);
insert(tree.root, 4);
insert(tree.root, 0);
insert(tree.root, 1);
preOrder(tree.root);